# This script deploys your website automatically
name: CI

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [ master ]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our master branch
    steps:
    - uses: actions/checkout@v2
    - name: Set-up Node
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - run: npm install
    # Run our deployment command
    - name: Deploying the static website to gh-pages
      run: npm run deploy
